/* Mock data — used when the Flask API server is not running. */
/* The API client falls back to this + localStorage automatically. */

const MOCK_POSTS = [
  {
    id: 1,
    platform: "twitter",
    content: "Excited to announce our new product launch! The future of social media automation is here 🚀 #Tech #Innovation #AI",
    status: "published",
    scheduled_at: "2026-05-10T09:00:00",
    published_at: "2026-05-10T09:00:05",
    platform_id: "1790123456789",
    error_message: null,
    retry_count: 0,
    created_at: "2026-05-09T14:22:00",
  },
  {
    id: 2,
    platform: "linkedin",
    content: "Proud to share that our team just hit a major milestone — 10,000 posts scheduled through our automation platform.\n\nKey lessons learned:\n• Start simple, iterate fast\n• Rate limits are your friend, not your enemy\n• Always store credentials securely\n\nWhat's your biggest challenge with social media automation?",
    status: "published",
    scheduled_at: "2026-05-10T14:30:00",
    published_at: "2026-05-10T14:30:03",
    platform_id: "urn:li:ugcPost:7194567890123",
    error_message: null,
    retry_count: 0,
    created_at: "2026-05-09T16:00:00",
  },
  {
    id: 3,
    platform: "twitter",
    content: "Quick tip: always test your API integrations with mocked HTTP responses before going live. Saves hours of debugging. 🧪 #DevTips",
    status: "pending",
    scheduled_at: "2026-05-12T10:00:00",
    published_at: null,
    platform_id: null,
    error_message: null,
    retry_count: 0,
    created_at: "2026-05-11T09:00:00",
  },
  {
    id: 4,
    platform: "linkedin",
    content: "Reflecting on five years of building in public — here are the three lessons that changed everything for me.\n\n1. Consistency beats virality every time\n2. Your niche audience is worth 100x a broad one\n3. The best content answers a question you wished someone had answered for you\n\nWhat lesson took you the longest to learn?",
    status: "pending",
    scheduled_at: "2026-05-13T14:00:00",
    published_at: null,
    platform_id: null,
    error_message: null,
    retry_count: 0,
    created_at: "2026-05-11T10:30:00",
  },
  {
    id: 5,
    platform: "twitter",
    content: "We're open-sourcing our rate-limit tracking module today. Link in bio. #OpenSource #Python",
    status: "pending",
    scheduled_at: "2026-05-14T08:00:00",
    published_at: null,
    platform_id: null,
    error_message: null,
    retry_count: 0,
    created_at: "2026-05-11T11:00:00",
  },
  {
    id: 6,
    platform: "twitter",
    content: "Authentication failed for this post — the API key had been rotated.",
    status: "failed",
    scheduled_at: "2026-05-09T12:00:00",
    published_at: null,
    platform_id: null,
    error_message: "Twitter auth error 401: Invalid or expired token.",
    retry_count: 3,
    created_at: "2026-05-08T20:00:00",
  },
  {
    id: 7,
    platform: "linkedin",
    content: "This post was cancelled before it could be published.",
    status: "cancelled",
    scheduled_at: "2026-05-11T16:00:00",
    published_at: null,
    platform_id: null,
    error_message: null,
    retry_count: 0,
    created_at: "2026-05-11T08:00:00",
  },
];

const MOCK_GENERATED = [
  {
    id: 1,
    topic: "AI productivity",
    platform: "twitter",
    tone: "casual",
    content: "AI just saved me 3 hours today. Here's how I used it to automate my content calendar — and why I'll never go back to manual scheduling 🧵",
    used: false,
    created_at: "2026-05-11T09:00:00",
  },
  {
    id: 2,
    topic: "AI productivity",
    platform: "linkedin",
    tone: "professional",
    content: "Artificial intelligence is reshaping how knowledge workers operate. Over the past quarter, teams using AI-assisted workflows reported a 40% reduction in repetitive tasks.\n\nThe key insight: AI doesn't replace judgment — it amplifies it.\n\nHow is your team integrating AI into daily workflows?",
    used: true,
    created_at: "2026-05-11T09:01:00",
  },
];

const MOCK_STATS = {
  total: 7,
  pending: 3,
  published: 2,
  failed: 1,
  cancelled: 1,
  next_due: "2026-05-12T10:00:00",
};
